package com.mark719.magicalcrops.config;

import java.io.*;
import net.minecraftforge.common.config.*;

public class ConfigDisable
{
    public static String vanilla;
    public static String monster;
    public static String MOD;
    public static boolean AIR;
    public static boolean COAL;
    public static boolean DYE;
    public static boolean EARTH;
    public static boolean FIRE;
    public static boolean MINICIO;
    public static boolean NATURE;
    public static boolean WATER;
    public static boolean REDSTONE;
    public static boolean GLOWSTONE;
    public static boolean OBSIDIAN;
    public static boolean NETHER;
    public static boolean IRON;
    public static boolean GOLD;
    public static boolean LAPIS;
    public static boolean EXPERIENCE;
    public static boolean QUARTZ;
    public static boolean DIAMOND;
    public static boolean EMERALD;
    public static boolean BLAZE;
    public static boolean CREEPER;
    public static boolean ENDERMAN;
    public static boolean GHAST;
    public static boolean SKELETON;
    public static boolean SLIME;
    public static boolean SPIDER;
    public static boolean WITHER;
    public static boolean CHICKEN;
    public static boolean COW;
    public static boolean PIG;
    public static boolean SHEEP;
    public static boolean ALUMINIUM;
    public static boolean ARDITE;
    public static boolean COBALT;
    public static boolean COPPER;
    public static boolean CERTUSQUARTZ;
    public static boolean LEAD;
    public static boolean NICKEL;
    public static boolean OSMIUM;
    public static boolean PERIDOT;
    public static boolean RUBY;
    public static boolean SAPPHIRE;
    public static boolean PLATINUM;
    public static boolean RUBBER;
    public static boolean SILVER;
    public static boolean TIN;
    public static boolean SULFUR;
    public static boolean YELLORITE;
    public static boolean ALUMITE;
    public static boolean BLIZZ;
    public static boolean BRONZE;
    public static boolean ELECTRUM;
    public static boolean ENDERIUM;
    public static boolean FLUIX;
    public static boolean INVAR;
    public static boolean LUMIUM;
    public static boolean MANASTEEL;
    public static boolean MANYULLYN;
    public static boolean SALTPETER;
    public static boolean SIGNALUM;
    public static boolean STEEL;
    public static boolean TERRASTEEL;
    
    public static void init(final File configFile) {
        final Configuration config = new Configuration(configFile);
        config.load();
        ConfigDisable.AIR = config.get(ConfigDisable.vanilla, "AIR CROP", true).getBoolean();
        ConfigDisable.COAL = config.get(ConfigDisable.vanilla, "COAL CROP", true).getBoolean();
        ConfigDisable.DYE = config.get(ConfigDisable.vanilla, "DYE CROP", true).getBoolean();
        ConfigDisable.EARTH = config.get(ConfigDisable.vanilla, "EARTH CROP", true).getBoolean();
        ConfigDisable.FIRE = config.get(ConfigDisable.vanilla, "FIRE CROP", true).getBoolean();
        ConfigDisable.MINICIO = config.get(ConfigDisable.vanilla, "MINICIO CROP", true).getBoolean();
        ConfigDisable.NATURE = config.get(ConfigDisable.vanilla, "NATURE CROP", true).getBoolean();
        ConfigDisable.WATER = config.get(ConfigDisable.vanilla, "WATER CROP", true).getBoolean();
        ConfigDisable.REDSTONE = config.get(ConfigDisable.vanilla, "REDSTONE CROP", true).getBoolean();
        ConfigDisable.GLOWSTONE = config.get(ConfigDisable.vanilla, "GLOWSTONE CROP", true).getBoolean();
        ConfigDisable.OBSIDIAN = config.get(ConfigDisable.vanilla, "OBSIDIAN CROP", true).getBoolean();
        ConfigDisable.NETHER = config.get(ConfigDisable.vanilla, "NETHER CROP", true).getBoolean();
        ConfigDisable.IRON = config.get(ConfigDisable.vanilla, "IRON CROP", true).getBoolean();
        ConfigDisable.GOLD = config.get(ConfigDisable.vanilla, "GOLD CROP", true).getBoolean();
        ConfigDisable.LAPIS = config.get(ConfigDisable.vanilla, "LAPIS CROP", true).getBoolean();
        ConfigDisable.EXPERIENCE = config.get(ConfigDisable.vanilla, "EXPERIENCE CROP", true).getBoolean();
        ConfigDisable.QUARTZ = config.get(ConfigDisable.vanilla, "QUARTZ CROP", true).getBoolean();
        ConfigDisable.DIAMOND = config.get(ConfigDisable.vanilla, "DIAMOND CROP", true).getBoolean();
        ConfigDisable.EMERALD = config.get(ConfigDisable.vanilla, "EMERALD CROP", true).getBoolean();
        ConfigDisable.BLAZE = config.get(ConfigDisable.monster, "BLAZE CROP", true).getBoolean();
        ConfigDisable.CREEPER = config.get(ConfigDisable.monster, "CREEPER CROP", true).getBoolean();
        ConfigDisable.ENDERMAN = config.get(ConfigDisable.monster, "ENDERMAN CROP", true).getBoolean();
        ConfigDisable.GHAST = config.get(ConfigDisable.monster, "GHAST CROP", true).getBoolean();
        ConfigDisable.SKELETON = config.get(ConfigDisable.monster, "SKELETON CROP", true).getBoolean();
        ConfigDisable.SLIME = config.get(ConfigDisable.monster, "SLIME CROP", true).getBoolean();
        ConfigDisable.SPIDER = config.get(ConfigDisable.monster, "SPIDER CROP", true).getBoolean();
        ConfigDisable.WITHER = config.get(ConfigDisable.monster, "WITHER CROP", true).getBoolean();
        ConfigDisable.CHICKEN = config.get(ConfigDisable.monster, "CHICKEN CROP", true).getBoolean();
        ConfigDisable.COW = config.get(ConfigDisable.monster, "COW CROP", true).getBoolean();
        ConfigDisable.PIG = config.get(ConfigDisable.monster, "PIG CROP", true).getBoolean();
        ConfigDisable.SHEEP = config.get(ConfigDisable.monster, "SHEEP CROP", true).getBoolean();
        ConfigDisable.ALUMINIUM = config.get(ConfigDisable.MOD, "ALUMINIUM CROP", true).getBoolean();
        ConfigDisable.ARDITE = config.get(ConfigDisable.MOD, "ARDITE CROP", true).getBoolean();
        ConfigDisable.COBALT = config.get(ConfigDisable.MOD, "COBALT CROP", true).getBoolean();
        ConfigDisable.COPPER = config.get(ConfigDisable.MOD, "COPPER CROP", true).getBoolean();
        ConfigDisable.CERTUSQUARTZ = config.get(ConfigDisable.MOD, "CERTUSQUARTZ CROP", true).getBoolean();
        ConfigDisable.LEAD = config.get(ConfigDisable.MOD, "LEAD CROP", true).getBoolean();
        ConfigDisable.NICKEL = config.get(ConfigDisable.MOD, "NICKEL CROP", true).getBoolean();
        ConfigDisable.OSMIUM = config.get(ConfigDisable.MOD, "OSMIUM CROP", true).getBoolean();
        ConfigDisable.PERIDOT = config.get(ConfigDisable.MOD, "PERIDOT CROP", true).getBoolean();
        ConfigDisable.RUBY = config.get(ConfigDisable.MOD, "RUBY CROP", true).getBoolean();
        ConfigDisable.SAPPHIRE = config.get(ConfigDisable.MOD, "SAPPHIRE CROP", true).getBoolean();
        ConfigDisable.PLATINUM = config.get(ConfigDisable.MOD, "PLATINUM CROP", true).getBoolean();
        ConfigDisable.RUBBER = config.get(ConfigDisable.MOD, "RUBBER CROP", true).getBoolean();
        ConfigDisable.SILVER = config.get(ConfigDisable.MOD, "SILVER CROP", true).getBoolean();
        ConfigDisable.TIN = config.get(ConfigDisable.MOD, "TIN CROP", true).getBoolean();
        ConfigDisable.SULFUR = config.get(ConfigDisable.MOD, "SULFUR CROP", true).getBoolean();
        ConfigDisable.YELLORITE = config.get(ConfigDisable.MOD, "YELLORITE CROP", true).getBoolean();
        ConfigDisable.ALUMITE = config.get(ConfigDisable.MOD, "ALUMITE CROP", true).getBoolean();
        ConfigDisable.BLIZZ = config.get(ConfigDisable.MOD, "BLIZZ CROP", true).getBoolean();
        ConfigDisable.BRONZE = config.get(ConfigDisable.MOD, "BRONZE CROP", true).getBoolean();
        ConfigDisable.ELECTRUM = config.get(ConfigDisable.MOD, "ELECTRUM CROP", true).getBoolean();
        ConfigDisable.ENDERIUM = config.get(ConfigDisable.MOD, "ENDERIUM CROP", true).getBoolean();
        ConfigDisable.FLUIX = config.get(ConfigDisable.MOD, "FLUIX CROP", true).getBoolean();
        ConfigDisable.INVAR = config.get(ConfigDisable.MOD, "INVAR CROP", true).getBoolean();
        ConfigDisable.LUMIUM = config.get(ConfigDisable.MOD, "LUMIUM CROP", true).getBoolean();
        ConfigDisable.MANASTEEL = config.get(ConfigDisable.MOD, "MANASTEEL CROP", true).getBoolean();
        ConfigDisable.MANYULLYN = config.get(ConfigDisable.MOD, "MANYULLYN CROP", true).getBoolean();
        ConfigDisable.SALTPETER = config.get(ConfigDisable.MOD, "SALTPETER CROP", true).getBoolean();
        ConfigDisable.SIGNALUM = config.get(ConfigDisable.MOD, "SIGNALUM CROP", true).getBoolean();
        ConfigDisable.STEEL = config.get(ConfigDisable.MOD, "STEEL CROP", true).getBoolean();
        ConfigDisable.TERRASTEEL = config.get(ConfigDisable.MOD, "TERRASTEEL CROP", true).getBoolean();
        config.save();
    }
    
    static {
        ConfigDisable.vanilla = "1 disable/enable vanilla crops, true = Enabled, false = Disabled";
        ConfigDisable.monster = "2 disable/enable monster/soul crops, true = Enabled, false = Disabled";
        ConfigDisable.MOD = "3 disable/enable mod compatible crops, true = Enabled, false = Disabled";
    }
}
