package com.mark719.magicalcrops.recipes;

import net.minecraft.item.*;
import net.minecraft.init.*;
import cpw.mods.fml.common.registry.*;
import net.minecraft.enchantment.*;
import com.mark719.magicalcrops.handlers.*;

public class EnchantmentRecipes
{
    static Item minicioEssence;
    static Item accioEssence;
    static Item crucioEssence;
    static Item imperioEssence;
    static Item zivicioEssence;
    static ItemStack airEssence;
    static ItemStack coalEssence;
    static ItemStack diamondEssence;
    static ItemStack dyeEssence;
    static ItemStack earthEssence;
    static ItemStack emeraldEssence;
    static ItemStack xpEssence;
    static ItemStack fireEssence;
    static ItemStack glowstoneEssence;
    static ItemStack goldEssence;
    static ItemStack ironEssence;
    static ItemStack lapisEssence;
    static ItemStack natureEssence;
    static ItemStack netherEssence;
    static ItemStack obsidianEssence;
    static ItemStack quartzEssence;
    static ItemStack redstoneEssence;
    static ItemStack taintedEssence;
    static ItemStack waterEssence;
    static ItemStack blazeEssence;
    static ItemStack creeperEssence;
    static ItemStack EndermanEssence;
    static ItemStack ghastEssence;
    static ItemStack skeletonEssence;
    static ItemStack slimeEssence;
    static ItemStack spiderEssence;
    static ItemStack witherEssence;
    static ItemStack cowEssence;
    static ItemStack pigEssence;
    static ItemStack chickenEssence;
    static ItemStack sheepEssence;
    static ItemStack xpBook1;
    static ItemStack xpBook2;
    static ItemStack xpBook3;
    static ItemStack xpBook4;
    static ItemStack xpBook5;
    
    public static void loadRecipes() {
        GameRegistry.addRecipe(EnchantmentRecipes.xpBook1, new Object[] { "XXX", "XZX", "XXX", 'X', EnchantmentRecipes.xpEssence, 'Z', Items.book });
        GameRegistry.addRecipe(EnchantmentRecipes.xpBook2, new Object[] { "XXX", "XZX", "XXX", 'X', EnchantmentRecipes.xpEssence, 'Z', EnchantmentRecipes.xpBook1 });
        GameRegistry.addRecipe(EnchantmentRecipes.xpBook3, new Object[] { "XXX", "XZX", "XXX", 'X', EnchantmentRecipes.xpEssence, 'Z', EnchantmentRecipes.xpBook2 });
        GameRegistry.addRecipe(EnchantmentRecipes.xpBook4, new Object[] { "XXX", "XZX", "XXX", 'X', EnchantmentRecipes.xpEssence, 'Z', EnchantmentRecipes.xpBook3 });
        GameRegistry.addRecipe(EnchantmentRecipes.xpBook5, new Object[] { "XXX", "XZX", "XXX", 'X', EnchantmentRecipes.xpEssence, 'Z', EnchantmentRecipes.xpBook4 });
        final EnchantmentData flame1 = new EnchantmentData(Enchantment.flame, 1);
        final ItemStack flameBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(flameBook1, flame1);
        GameRegistry.addRecipe(flameBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.fireEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData efficiency1 = new EnchantmentData(Enchantment.efficiency, 1);
        final ItemStack efficiencyBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(efficiencyBook1, efficiency1);
        GameRegistry.addRecipe(efficiencyBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.redstoneEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData efficiency2 = new EnchantmentData(Enchantment.efficiency, 2);
        final ItemStack efficiencyBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(efficiencyBook2, efficiency2);
        GameRegistry.addRecipe(efficiencyBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.redstoneEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData efficiency3 = new EnchantmentData(Enchantment.efficiency, 3);
        final ItemStack efficiencyBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(efficiencyBook3, efficiency3);
        GameRegistry.addRecipe(efficiencyBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.redstoneEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData efficiency4 = new EnchantmentData(Enchantment.efficiency, 4);
        final ItemStack efficiencyBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(efficiencyBook4, efficiency4);
        GameRegistry.addRecipe(efficiencyBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.redstoneEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData efficiency5 = new EnchantmentData(Enchantment.efficiency, 5);
        final ItemStack efficiencyBook5 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(efficiencyBook5, efficiency5);
        GameRegistry.addRecipe(efficiencyBook5, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.redstoneEssence, 'Y', EnchantmentRecipes.xpBook5 });
        final EnchantmentData silk1 = new EnchantmentData(Enchantment.silkTouch, 1);
        final ItemStack silkBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(silkBook1, silk1);
        GameRegistry.addRecipe(silkBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.emeraldEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData unbreaking1 = new EnchantmentData(Enchantment.unbreaking, 1);
        final ItemStack unbreakingBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(unbreakingBook1, unbreaking1);
        GameRegistry.addRecipe(unbreakingBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.obsidianEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData unbreaking2 = new EnchantmentData(Enchantment.unbreaking, 2);
        final ItemStack unbreakingBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(unbreakingBook2, unbreaking2);
        GameRegistry.addRecipe(unbreakingBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.obsidianEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData unbreaking3 = new EnchantmentData(Enchantment.unbreaking, 3);
        final ItemStack unbreakingBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(unbreakingBook3, unbreaking3);
        GameRegistry.addRecipe(unbreakingBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.obsidianEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData fortune1 = new EnchantmentData(Enchantment.fortune, 1);
        final ItemStack fortuneBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(fortuneBook1, fortune1);
        GameRegistry.addRecipe(fortuneBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.lapisEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData fortune2 = new EnchantmentData(Enchantment.fortune, 2);
        final ItemStack fortuneBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(fortuneBook2, fortune2);
        GameRegistry.addRecipe(fortuneBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.lapisEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData fortune3 = new EnchantmentData(Enchantment.fortune, 3);
        final ItemStack fortuneBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(fortuneBook3, fortune3);
        GameRegistry.addRecipe(fortuneBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.lapisEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData protection1 = new EnchantmentData(Enchantment.protection, 1);
        final ItemStack protectionBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(protectionBook1, protection1);
        GameRegistry.addRecipe(protectionBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.diamondEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData protection2 = new EnchantmentData(Enchantment.protection, 2);
        final ItemStack protectionBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(protectionBook2, protection2);
        GameRegistry.addRecipe(protectionBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.diamondEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData protection3 = new EnchantmentData(Enchantment.protection, 3);
        final ItemStack protectionBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(protectionBook3, protection3);
        GameRegistry.addRecipe(protectionBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.diamondEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData protection4 = new EnchantmentData(Enchantment.protection, 4);
        final ItemStack protectionBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(protectionBook4, protection4);
        GameRegistry.addRecipe(protectionBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.diamondEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData fireprotection1 = new EnchantmentData(Enchantment.fireProtection, 1);
        final ItemStack fireprotectionBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(fireprotectionBook1, fireprotection1);
        GameRegistry.addRecipe(fireprotectionBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.blazeEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData fireprotection2 = new EnchantmentData(Enchantment.fireProtection, 2);
        final ItemStack fireprotectionBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(fireprotectionBook2, fireprotection2);
        GameRegistry.addRecipe(fireprotectionBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.blazeEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData fireprotection3 = new EnchantmentData(Enchantment.fireProtection, 3);
        final ItemStack fireprotectionBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(fireprotectionBook3, fireprotection3);
        GameRegistry.addRecipe(fireprotectionBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.blazeEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData fireprotection4 = new EnchantmentData(Enchantment.fireProtection, 4);
        final ItemStack fireprotectionBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(fireprotectionBook4, fireprotection4);
        GameRegistry.addRecipe(fireprotectionBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.blazeEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData feather1 = new EnchantmentData(Enchantment.featherFalling, 1);
        final ItemStack featherBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(featherBook1, feather1);
        GameRegistry.addRecipe(featherBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.chickenEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData feather2 = new EnchantmentData(Enchantment.featherFalling, 2);
        final ItemStack featherBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(featherBook2, feather2);
        GameRegistry.addRecipe(featherBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.chickenEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData feather3 = new EnchantmentData(Enchantment.featherFalling, 3);
        final ItemStack featherBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(featherBook3, feather3);
        GameRegistry.addRecipe(featherBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.chickenEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData feather4 = new EnchantmentData(Enchantment.featherFalling, 4);
        final ItemStack featherBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(featherBook4, feather4);
        GameRegistry.addRecipe(featherBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.chickenEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData blastprotection1 = new EnchantmentData(Enchantment.blastProtection, 1);
        final ItemStack blastprotectionBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(blastprotectionBook1, blastprotection1);
        GameRegistry.addRecipe(blastprotectionBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.creeperEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData blastprotection2 = new EnchantmentData(Enchantment.blastProtection, 2);
        final ItemStack blastprotectionBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(blastprotectionBook2, blastprotection2);
        GameRegistry.addRecipe(blastprotectionBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.creeperEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData blastprotection3 = new EnchantmentData(Enchantment.blastProtection, 3);
        final ItemStack blastprotectionBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(blastprotectionBook3, blastprotection3);
        GameRegistry.addRecipe(blastprotectionBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.creeperEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData blastprotection4 = new EnchantmentData(Enchantment.blastProtection, 4);
        final ItemStack blastprotectionBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(blastprotectionBook4, blastprotection4);
        GameRegistry.addRecipe(blastprotectionBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.creeperEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData projectileprotection1 = new EnchantmentData(Enchantment.projectileProtection, 1);
        final ItemStack projectileprotectionBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(projectileprotectionBook1, projectileprotection1);
        GameRegistry.addRecipe(projectileprotectionBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.skeletonEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData projectileprotection2 = new EnchantmentData(Enchantment.projectileProtection, 2);
        final ItemStack projectileprotectionBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(projectileprotectionBook2, projectileprotection2);
        GameRegistry.addRecipe(projectileprotectionBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.skeletonEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData projectileprotection3 = new EnchantmentData(Enchantment.projectileProtection, 3);
        final ItemStack projectileprotectionBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(projectileprotectionBook3, projectileprotection3);
        GameRegistry.addRecipe(projectileprotectionBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.skeletonEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData projectileprotection4 = new EnchantmentData(Enchantment.projectileProtection, 4);
        final ItemStack projectileprotectionBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(projectileprotectionBook4, projectileprotection4);
        GameRegistry.addRecipe(projectileprotectionBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.skeletonEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData respiration1 = new EnchantmentData(Enchantment.respiration, 1);
        final ItemStack respirationBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(respirationBook1, respiration1);
        GameRegistry.addRecipe(respirationBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.airEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData respiration2 = new EnchantmentData(Enchantment.respiration, 2);
        final ItemStack respirationBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(respirationBook2, respiration2);
        GameRegistry.addRecipe(respirationBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.airEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData respiration3 = new EnchantmentData(Enchantment.respiration, 3);
        final ItemStack respirationBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(respirationBook3, respiration3);
        GameRegistry.addRecipe(respirationBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.airEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData aqua1 = new EnchantmentData(Enchantment.aquaAffinity, 1);
        final ItemStack aquaBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(aquaBook1, aqua1);
        GameRegistry.addRecipe(aquaBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.waterEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData thorns1 = new EnchantmentData(Enchantment.thorns, 1);
        final ItemStack thornsBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(thornsBook1, thorns1);
        GameRegistry.addRecipe(thornsBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.natureEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData thorns2 = new EnchantmentData(Enchantment.thorns, 2);
        final ItemStack thornsBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(thornsBook2, thorns2);
        GameRegistry.addRecipe(thornsBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.natureEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData thorns3 = new EnchantmentData(Enchantment.thorns, 3);
        final ItemStack thornsBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(thornsBook3, thorns3);
        GameRegistry.addRecipe(thornsBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.natureEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData sharpness1 = new EnchantmentData(Enchantment.sharpness, 1);
        final ItemStack sharpnessBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(sharpnessBook1, sharpness1);
        GameRegistry.addRecipe(sharpnessBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.quartzEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData sharpness2 = new EnchantmentData(Enchantment.sharpness, 2);
        final ItemStack sharpnessBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(sharpnessBook2, sharpness2);
        GameRegistry.addRecipe(sharpnessBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.quartzEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData sharpness3 = new EnchantmentData(Enchantment.sharpness, 3);
        final ItemStack sharpnessBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(sharpnessBook3, sharpness3);
        GameRegistry.addRecipe(sharpnessBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.quartzEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData sharpness4 = new EnchantmentData(Enchantment.sharpness, 4);
        final ItemStack sharpnessBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(sharpnessBook4, sharpness4);
        GameRegistry.addRecipe(sharpnessBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.quartzEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData sharpness5 = new EnchantmentData(Enchantment.sharpness, 5);
        final ItemStack sharpnessBook5 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(sharpnessBook5, sharpness5);
        GameRegistry.addRecipe(sharpnessBook5, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.quartzEssence, 'Y', EnchantmentRecipes.xpBook5 });
        final EnchantmentData smite1 = new EnchantmentData(Enchantment.smite, 1);
        final ItemStack smiteBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(smiteBook1, smite1);
        GameRegistry.addRecipe(smiteBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.netherEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData smite2 = new EnchantmentData(Enchantment.smite, 2);
        final ItemStack smiteBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(smiteBook2, smite2);
        GameRegistry.addRecipe(smiteBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.netherEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData smite3 = new EnchantmentData(Enchantment.smite, 3);
        final ItemStack smiteBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(smiteBook3, smite3);
        GameRegistry.addRecipe(smiteBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.netherEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData smite4 = new EnchantmentData(Enchantment.smite, 4);
        final ItemStack smiteBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(smiteBook4, smite4);
        GameRegistry.addRecipe(smiteBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.netherEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData smite5 = new EnchantmentData(Enchantment.smite, 5);
        final ItemStack smiteBook5 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(smiteBook5, smite5);
        GameRegistry.addRecipe(smiteBook5, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.netherEssence, 'Y', EnchantmentRecipes.xpBook5 });
        final EnchantmentData bane1 = new EnchantmentData(Enchantment.baneOfArthropods, 1);
        final ItemStack baneBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(baneBook1, bane1);
        GameRegistry.addRecipe(baneBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.spiderEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData bane2 = new EnchantmentData(Enchantment.baneOfArthropods, 2);
        final ItemStack baneBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(baneBook2, bane2);
        GameRegistry.addRecipe(baneBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.spiderEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData bane3 = new EnchantmentData(Enchantment.baneOfArthropods, 3);
        final ItemStack baneBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(baneBook3, bane3);
        GameRegistry.addRecipe(baneBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.spiderEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData bane4 = new EnchantmentData(Enchantment.baneOfArthropods, 4);
        final ItemStack baneBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(baneBook4, bane4);
        GameRegistry.addRecipe(baneBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.spiderEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData bane5 = new EnchantmentData(Enchantment.baneOfArthropods, 5);
        final ItemStack baneBook5 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(baneBook5, bane5);
        GameRegistry.addRecipe(baneBook5, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.spiderEssence, 'Y', EnchantmentRecipes.xpBook5 });
        final EnchantmentData knockback1 = new EnchantmentData(Enchantment.knockback, 1);
        final ItemStack knockbackBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(knockbackBook1, knockback1);
        GameRegistry.addRecipe(knockbackBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.ironEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData knockback2 = new EnchantmentData(Enchantment.knockback, 2);
        final ItemStack knockbackBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(knockbackBook2, knockback2);
        GameRegistry.addRecipe(knockbackBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.ironEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData looting1 = new EnchantmentData(Enchantment.looting, 1);
        final ItemStack lootingBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(lootingBook1, looting1);
        GameRegistry.addRecipe(lootingBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.goldEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData looting2 = new EnchantmentData(Enchantment.looting, 2);
        final ItemStack lootingBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(lootingBook2, looting2);
        GameRegistry.addRecipe(lootingBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.goldEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData looting3 = new EnchantmentData(Enchantment.looting, 3);
        final ItemStack lootingBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(lootingBook3, looting3);
        GameRegistry.addRecipe(lootingBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.goldEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData power1 = new EnchantmentData(Enchantment.power, 1);
        final ItemStack powerBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(powerBook1, power1);
        GameRegistry.addRecipe(powerBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.coalEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData power2 = new EnchantmentData(Enchantment.power, 2);
        final ItemStack powerBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(powerBook2, power2);
        GameRegistry.addRecipe(powerBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.coalEssence, 'Y', EnchantmentRecipes.xpBook2 });
        final EnchantmentData power3 = new EnchantmentData(Enchantment.power, 3);
        final ItemStack powerBook3 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(powerBook3, power3);
        GameRegistry.addRecipe(powerBook3, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.coalEssence, 'Y', EnchantmentRecipes.xpBook3 });
        final EnchantmentData power4 = new EnchantmentData(Enchantment.power, 4);
        final ItemStack powerBook4 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(powerBook4, power4);
        GameRegistry.addRecipe(powerBook4, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.coalEssence, 'Y', EnchantmentRecipes.xpBook4 });
        final EnchantmentData power5 = new EnchantmentData(Enchantment.power, 5);
        final ItemStack powerBook5 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(powerBook5, power5);
        GameRegistry.addRecipe(powerBook5, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.coalEssence, 'Y', EnchantmentRecipes.xpBook5 });
        final EnchantmentData infinity1 = new EnchantmentData(Enchantment.infinity, 1);
        final ItemStack infinityBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(infinityBook1, infinity1);
        GameRegistry.addRecipe(infinityBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.slimeEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData punch1 = new EnchantmentData(Enchantment.punch, 1);
        final ItemStack punchBook1 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(punchBook1, punch1);
        GameRegistry.addRecipe(punchBook1, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.glowstoneEssence, 'Y', EnchantmentRecipes.xpBook1 });
        final EnchantmentData punch2 = new EnchantmentData(Enchantment.punch, 2);
        final ItemStack punchBook2 = new ItemStack((Item)Items.enchanted_book, 1);
        Items.enchanted_book.addEnchantment(punchBook2, punch2);
        GameRegistry.addRecipe(punchBook2, new Object[] { "XXX", "XYX", "XXX", 'X', EnchantmentRecipes.glowstoneEssence, 'Y', EnchantmentRecipes.xpBook2 });
    }
    
    static {
        EnchantmentRecipes.minicioEssence = Essence.MinicioEssence;
        EnchantmentRecipes.accioEssence = Essence.AccioEssence;
        EnchantmentRecipes.crucioEssence = Essence.CrucioEssence;
        EnchantmentRecipes.imperioEssence = Essence.ImperioEssence;
        EnchantmentRecipes.zivicioEssence = Essence.ZivicioEssence;
        EnchantmentRecipes.airEssence = new ItemStack(Essence.AirEssence, 1, 0);
        EnchantmentRecipes.coalEssence = new ItemStack(Essence.CoalEssence, 1, 0);
        EnchantmentRecipes.diamondEssence = new ItemStack(Essence.DiamondEssence, 1, 0);
        EnchantmentRecipes.dyeEssence = new ItemStack(Essence.DyeEssence, 1, 0);
        EnchantmentRecipes.earthEssence = new ItemStack(Essence.EarthEssence, 1, 0);
        EnchantmentRecipes.emeraldEssence = new ItemStack(Essence.EmeraldEssence, 1, 0);
        EnchantmentRecipes.xpEssence = new ItemStack(Essence.ExperienceEssence, 1, 0);
        EnchantmentRecipes.fireEssence = new ItemStack(Essence.FireEssence, 1, 0);
        EnchantmentRecipes.glowstoneEssence = new ItemStack(Essence.GlowstoneEssence, 1, 0);
        EnchantmentRecipes.goldEssence = new ItemStack(Essence.GoldEssence, 1, 0);
        EnchantmentRecipes.ironEssence = new ItemStack(Essence.IronEssence, 1, 0);
        EnchantmentRecipes.lapisEssence = new ItemStack(Essence.LapisEssence, 1, 0);
        EnchantmentRecipes.natureEssence = new ItemStack(Essence.NatureEssence, 1, 0);
        EnchantmentRecipes.netherEssence = new ItemStack(Essence.NetherEssence, 1, 0);
        EnchantmentRecipes.obsidianEssence = new ItemStack(Essence.ObsidianEssence, 1, 0);
        EnchantmentRecipes.quartzEssence = new ItemStack(Essence.QuartzEssence, 1, 0);
        EnchantmentRecipes.redstoneEssence = new ItemStack(Essence.RedstoneEssence, 1, 0);
        EnchantmentRecipes.taintedEssence = new ItemStack(Essence.TaintedEssence, 1, 0);
        EnchantmentRecipes.waterEssence = new ItemStack(Essence.WaterEssence, 1, 0);
        EnchantmentRecipes.blazeEssence = new ItemStack(Essence.BlazeEssence, 1, 0);
        EnchantmentRecipes.creeperEssence = new ItemStack(Essence.CreeperEssence, 1, 0);
        EnchantmentRecipes.EndermanEssence = new ItemStack(Essence.EndermanEssence, 1, 0);
        EnchantmentRecipes.ghastEssence = new ItemStack(Essence.GhastEssence, 1, 0);
        EnchantmentRecipes.skeletonEssence = new ItemStack(Essence.SkeletonEssence, 1, 0);
        EnchantmentRecipes.slimeEssence = new ItemStack(Essence.SlimeEssence, 1, 0);
        EnchantmentRecipes.spiderEssence = new ItemStack(Essence.SpiderEssence, 1, 0);
        EnchantmentRecipes.witherEssence = new ItemStack(Essence.WitherEssence, 1, 0);
        EnchantmentRecipes.cowEssence = new ItemStack(Essence.CowEssence, 1, 0);
        EnchantmentRecipes.pigEssence = new ItemStack(Essence.PigEssence, 1, 0);
        EnchantmentRecipes.chickenEssence = new ItemStack(Essence.ChickenEssence, 1, 0);
        EnchantmentRecipes.sheepEssence = new ItemStack(Essence.SheepEssence, 1, 0);
        EnchantmentRecipes.xpBook1 = new ItemStack(MItems.ExperienceBook, 1, 0);
        EnchantmentRecipes.xpBook2 = new ItemStack(MItems.ExperienceBook, 1, 1);
        EnchantmentRecipes.xpBook3 = new ItemStack(MItems.ExperienceBook, 1, 2);
        EnchantmentRecipes.xpBook4 = new ItemStack(MItems.ExperienceBook, 1, 3);
        EnchantmentRecipes.xpBook5 = new ItemStack(MItems.ExperienceBook, 1, 4);
    }
}
