package com.mark719.magicalcrops.recipes;

import net.minecraft.item.*;
import com.mark719.magicalcrops.config.*;
import cpw.mods.fml.common.registry.*;
import net.minecraft.init.*;
import net.minecraft.block.*;
import com.mark719.magicalcrops.handlers.*;

public class ResourceRecipes
{
    static Item minicioEssence;
    static Item accioEssence;
    static Item crucioEssence;
    static Item imperioEssence;
    static Item zivicioEssence;
    static ItemStack airEssence;
    static ItemStack coalEssence;
    static ItemStack diamondEssence;
    static ItemStack dyeEssence;
    static ItemStack earthEssence;
    static ItemStack emeraldEssence;
    static ItemStack xpEssence;
    static ItemStack fireEssence;
    static ItemStack glowstoneEssence;
    static ItemStack goldEssence;
    static ItemStack ironEssence;
    static ItemStack lapisEssence;
    static ItemStack natureEssence;
    static ItemStack netherEssence;
    static ItemStack obsidianEssence;
    static ItemStack quartzEssence;
    static ItemStack redstoneEssence;
    static ItemStack taintedEssence;
    static ItemStack waterEssence;
    static ItemStack blazeEssence;
    static ItemStack creeperEssence;
    static ItemStack endermanEssence;
    static ItemStack ghastEssence;
    static ItemStack skeletonEssence;
    static ItemStack slimeEssence;
    static ItemStack spiderEssence;
    static ItemStack witherEssence;
    static ItemStack chickenEssence;
    static ItemStack cowEssence;
    static ItemStack pigEssence;
    static ItemStack sheepEssence;
    
    public static void loadRecipes() {
        GameRegistry.addRecipe(new ItemStack(Items.coal, ConfigCrafting.outPutCoal), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.coalEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 0), new Object[] { "XXX", "   ", "   ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 1), new Object[] { "   ", "XXX", "   ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 2), new Object[] { "   ", "   ", "XXX", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 5), new Object[] { " X ", " X ", " X ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 6), new Object[] { "X  ", "X  ", "X  ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 7), new Object[] { "X  ", " X ", "  X", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 8), new Object[] { " X ", " X ", "X  ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 9), new Object[] { "XX ", "X  ", "   ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 10), new Object[] { " XX", "X  ", "   ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 11), new Object[] { "   ", " X ", "X X", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 12), new Object[] { "XX ", " X ", "   ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 13), new Object[] { " X ", "X  ", " X ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutDye, 14), new Object[] { "  X", " X ", " X ", 'X', ResourceRecipes.dyeEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.mossy_cobblestone, ConfigCrafting.outPutMossyCobble), new Object[] { "XXX", "XYX", "XXX", 'X', Blocks.cobblestone, 'Y', ResourceRecipes.natureEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.stonebrick, ConfigCrafting.outPutMossyBrick, 1), new Object[] { "XXX", "XYX", "XXX", 'Y', ResourceRecipes.natureEssence, 'X', Blocks.stonebrick });
        GameRegistry.addRecipe(new ItemStack(Blocks.vine, ConfigCrafting.outPutVines), new Object[] { "X X", "XXX", "X X", 'X', ResourceRecipes.natureEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.waterlily, ConfigCrafting.outPutLily), new Object[] { " X ", "XXX", "X X", 'X', ResourceRecipes.natureEssence });
        GameRegistry.addRecipe(new ItemStack((Block)Blocks.mycelium, ConfigCrafting.outPutMycelium), new Object[] { "YXY", "XZX", "YXY", 'X', ResourceRecipes.natureEssence, 'Y', Blocks.dirt, 'Z', Blocks.brown_mushroom });
        GameRegistry.addRecipe(new ItemStack((Block)Blocks.mycelium, ConfigCrafting.outPutMycelium), new Object[] { "YXY", "XZX", "YXY", 'X', ResourceRecipes.natureEssence, 'Y', Blocks.dirt, 'Z', Blocks.red_mushroom });
        GameRegistry.addRecipe(new ItemStack(Blocks.cactus, ConfigCrafting.outPutCactus), new Object[] { "XX ", "XX ", "XX ", 'X', ResourceRecipes.natureEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.log, ConfigCrafting.outPutWood, 0), new Object[] { "YX ", "XX ", 'X', ResourceRecipes.natureEssence, 'Y', ResourceRecipes.waterEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.log, ConfigCrafting.outPutWood, 1), new Object[] { "XY ", "XX ", 'X', ResourceRecipes.natureEssence, 'Y', ResourceRecipes.waterEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.log, ConfigCrafting.outPutWood, 2), new Object[] { "XX ", "YX ", 'X', ResourceRecipes.natureEssence, 'Y', ResourceRecipes.waterEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.log, ConfigCrafting.outPutWood, 3), new Object[] { "XX ", "XY ", 'X', ResourceRecipes.natureEssence, 'Y', ResourceRecipes.waterEssence });
        GameRegistry.addRecipe(new ItemStack(Items.snowball, ConfigCrafting.outPutSnowBalls), new Object[] { "XY ", "YX ", 'X', ResourceRecipes.waterEssence, 'Y', ResourceRecipes.airEssence });
        GameRegistry.addRecipe(new ItemStack(Items.lava_bucket, 1), new Object[] { " X ", "XYX", " X ", 'X', ResourceRecipes.fireEssence, 'Y', new ItemStack(Items.bucket, 1) });
        GameRegistry.addRecipe(new ItemStack(Items.water_bucket, 1), new Object[] { " X ", "XYX", " X ", 'X', ResourceRecipes.waterEssence, 'Y', new ItemStack(Items.bucket, 1) });
        GameRegistry.addRecipe(new ItemStack(Items.clay_ball, ConfigCrafting.outPutClayBall), new Object[] { "XY ", "YX ", 'X', ResourceRecipes.waterEssence, 'Y', ResourceRecipes.earthEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.cobblestone, ConfigCrafting.outPutCobblestone), new Object[] { "XY ", "YX ", 'X', ResourceRecipes.fireEssence, 'Y', ResourceRecipes.earthEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.dirt, ConfigCrafting.outPutDirt), new Object[] { "XXX", "X X", "XXX", 'X', ResourceRecipes.earthEssence });
        GameRegistry.addRecipe(new ItemStack((Block)Blocks.sand, ConfigCrafting.outPutSand), new Object[] { "YX ", "XY ", 'X', ResourceRecipes.fireEssence, 'Y', ResourceRecipes.earthEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.gravel, ConfigCrafting.outPutGravel), new Object[] { "YY ", "XX ", 'X', ResourceRecipes.fireEssence, 'Y', ResourceRecipes.earthEssence });
        GameRegistry.addRecipe(new ItemStack(Items.redstone, ConfigCrafting.outPutRedstone), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.redstoneEssence });
        GameRegistry.addRecipe(new ItemStack(Items.glowstone_dust, ConfigCrafting.outPutGlowstone), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.glowstoneEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.obsidian, ConfigCrafting.outPutObsidian), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.obsidianEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.soul_sand, ConfigCrafting.outPutSoul), new Object[] { "XXX", "X X", "XXX", 'X', ResourceRecipes.netherEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.netherrack, ConfigCrafting.outPutNether), new Object[] { "XX", "XX", 'X', ResourceRecipes.netherEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.nether_brick, ConfigCrafting.outPutNetherbrick), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.netherEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.iron_ore, ConfigCrafting.outPutIron), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.ironEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.gold_ore, ConfigCrafting.outPutGold), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.goldEssence });
        GameRegistry.addRecipe(new ItemStack(Items.dye, ConfigCrafting.outPutLapis, 4), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.lapisEssence });
        GameRegistry.addRecipe(new ItemStack(Items.quartz, ConfigCrafting.outPutQuartz), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.quartzEssence });
        GameRegistry.addRecipe(new ItemStack(Items.experience_bottle, ConfigCrafting.outPutXP), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.xpEssence });
        GameRegistry.addRecipe(new ItemStack(Items.emerald, ConfigCrafting.outPutEmerald), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.emeraldEssence });
        GameRegistry.addRecipe(new ItemStack(Items.diamond, ConfigCrafting.outPutDiamond), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.diamondEssence });
        GameRegistry.addRecipe(new ItemStack(Items.leather, ConfigCrafting.outPutCowLeather), new Object[] { "XXX", "X X", "XXX", 'X', ResourceRecipes.cowEssence });
        GameRegistry.addRecipe(new ItemStack(Items.beef, ConfigCrafting.outPutCowBeef), new Object[] { "XX", "XX", 'X', ResourceRecipes.cowEssence });
        GameRegistry.addRecipe(new ItemStack(Items.milk_bucket, 1), new Object[] { " X ", "XYX", " X ", 'X', ResourceRecipes.cowEssence, 'Y', Items.bucket });
        GameRegistry.addRecipe(new ItemStack(Items.porkchop, ConfigCrafting.outPutPigPork), new Object[] { "XX", "XX", 'X', ResourceRecipes.pigEssence });
        GameRegistry.addRecipe(new ItemStack(Items.chicken, ConfigCrafting.outPutChicken), new Object[] { "XX", "XX", 'X', ResourceRecipes.chickenEssence });
        GameRegistry.addRecipe(new ItemStack(Items.feather, ConfigCrafting.outPutFeather), new Object[] { "XXX", "X X", "XXX", 'X', ResourceRecipes.chickenEssence });
        GameRegistry.addRecipe(new ItemStack(Items.egg, ConfigCrafting.outPutEggs), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.chickenEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.wool, ConfigCrafting.outPutSheepWool), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.sheepEssence });
        GameRegistry.addRecipe(new ItemStack(Items.skull, ConfigCrafting.outPutCreeperHead, 4), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.creeperEssence });
        GameRegistry.addRecipe(new ItemStack(Items.gunpowder, ConfigCrafting.outPutCreeperGun), new Object[] { "XXX", "X X", "XXX", 'X', ResourceRecipes.creeperEssence });
        GameRegistry.addRecipe(new ItemStack(Items.blaze_rod, ConfigCrafting.outPutBlazerod), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.blazeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.ender_pearl, ConfigCrafting.outPutEnderPearl), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.endermanEssence });
        GameRegistry.addRecipe(new ItemStack(Blocks.end_stone, 8), new Object[] { "XXX", "XYX", "XXX", 'Y', ResourceRecipes.endermanEssence, 'X', Blocks.stone });
        GameRegistry.addRecipe(new ItemStack(Items.skull, ConfigCrafting.outPutSkeleSkull, 0), new Object[] { "XXX", "X X", "XXX", 'X', ResourceRecipes.skeletonEssence });
        GameRegistry.addRecipe(new ItemStack(Items.bone, ConfigCrafting.outPutBones), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.skeletonEssence });
        GameRegistry.addRecipe(new ItemStack(Items.skull, ConfigCrafting.outPutWitherSkull, 1), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.witherEssence });
        GameRegistry.addRecipe(new ItemStack(Items.slime_ball, ConfigCrafting.outPutSlimeBall), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.slimeEssence });
        GameRegistry.addRecipe(new ItemStack(Items.string, ConfigCrafting.outPutSpiderString), new Object[] { "XXX", "X X", "XXX", 'X', ResourceRecipes.spiderEssence });
        GameRegistry.addRecipe(new ItemStack(Items.spider_eye, ConfigCrafting.outPutSpiderEye), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.spiderEssence });
        GameRegistry.addRecipe(new ItemStack(Items.ghast_tear, ConfigCrafting.outPutGhastTear), new Object[] { "XXX", "XXX", "XXX", 'X', ResourceRecipes.ghastEssence });
        GameRegistry.addRecipe(new ItemStack(Items.record_13, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 11) });
        GameRegistry.addRecipe(new ItemStack(Items.record_cat, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 2) });
        GameRegistry.addRecipe(new ItemStack(Items.record_blocks, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 14) });
        GameRegistry.addRecipe(new ItemStack(Items.record_chirp, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 1) });
        GameRegistry.addRecipe(new ItemStack(Items.record_strad, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 15) });
        GameRegistry.addRecipe(new ItemStack(Items.record_ward, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 6) });
        GameRegistry.addRecipe(new ItemStack(Items.record_far, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 10) });
        GameRegistry.addRecipe(new ItemStack(Items.record_mall, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 5) });
        GameRegistry.addRecipe(new ItemStack(Items.record_mellohi, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 9) });
        GameRegistry.addRecipe(new ItemStack(Items.record_stal, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 0) });
        GameRegistry.addRecipe(new ItemStack(Items.record_11, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 8) });
        GameRegistry.addRecipe(new ItemStack(Items.record_wait, 1), new Object[] { "XYX", "YZY", "XYX", 'X', ResourceRecipes.skeletonEssence, 'Y', ResourceRecipes.creeperEssence, 'Z', new ItemStack(Items.dye, 1, 4) });
        GameRegistry.addRecipe(new ItemStack(Blocks.mob_spawner, 1, 61), new Object[] { "XXX", "XYX", "XXX", 'X', ResourceRecipes.blazeEssence, 'Y', MBlocks.WitherProof });
    }
    
    static {
        ResourceRecipes.minicioEssence = Essence.MinicioEssence;
        ResourceRecipes.accioEssence = Essence.AccioEssence;
        ResourceRecipes.crucioEssence = Essence.CrucioEssence;
        ResourceRecipes.imperioEssence = Essence.ImperioEssence;
        ResourceRecipes.zivicioEssence = Essence.ZivicioEssence;
        ResourceRecipes.airEssence = new ItemStack(Essence.AirEssence, 1, 0);
        ResourceRecipes.coalEssence = new ItemStack(Essence.CoalEssence, 1, 0);
        ResourceRecipes.diamondEssence = new ItemStack(Essence.DiamondEssence, 1, 0);
        ResourceRecipes.dyeEssence = new ItemStack(Essence.DyeEssence, 1, 0);
        ResourceRecipes.earthEssence = new ItemStack(Essence.EarthEssence, 1, 0);
        ResourceRecipes.emeraldEssence = new ItemStack(Essence.EmeraldEssence, 1, 0);
        ResourceRecipes.xpEssence = new ItemStack(Essence.ExperienceEssence, 1, 0);
        ResourceRecipes.fireEssence = new ItemStack(Essence.FireEssence, 1, 0);
        ResourceRecipes.glowstoneEssence = new ItemStack(Essence.GlowstoneEssence, 1, 0);
        ResourceRecipes.goldEssence = new ItemStack(Essence.GoldEssence, 1, 0);
        ResourceRecipes.ironEssence = new ItemStack(Essence.IronEssence, 1, 0);
        ResourceRecipes.lapisEssence = new ItemStack(Essence.LapisEssence, 1, 0);
        ResourceRecipes.natureEssence = new ItemStack(Essence.NatureEssence, 1, 0);
        ResourceRecipes.netherEssence = new ItemStack(Essence.NetherEssence, 1, 0);
        ResourceRecipes.obsidianEssence = new ItemStack(Essence.ObsidianEssence, 1, 0);
        ResourceRecipes.quartzEssence = new ItemStack(Essence.QuartzEssence, 1, 0);
        ResourceRecipes.redstoneEssence = new ItemStack(Essence.RedstoneEssence, 1, 0);
        ResourceRecipes.taintedEssence = new ItemStack(Essence.TaintedEssence, 1, 0);
        ResourceRecipes.waterEssence = new ItemStack(Essence.WaterEssence, 1, 0);
        ResourceRecipes.blazeEssence = new ItemStack(Essence.BlazeEssence, 1, 0);
        ResourceRecipes.creeperEssence = new ItemStack(Essence.CreeperEssence, 1, 0);
        ResourceRecipes.endermanEssence = new ItemStack(Essence.EndermanEssence, 1, 0);
        ResourceRecipes.ghastEssence = new ItemStack(Essence.GhastEssence, 1, 0);
        ResourceRecipes.skeletonEssence = new ItemStack(Essence.SkeletonEssence, 1, 0);
        ResourceRecipes.slimeEssence = new ItemStack(Essence.SlimeEssence, 1, 0);
        ResourceRecipes.spiderEssence = new ItemStack(Essence.SpiderEssence, 1, 0);
        ResourceRecipes.witherEssence = new ItemStack(Essence.WitherEssence, 1, 0);
        ResourceRecipes.chickenEssence = new ItemStack(Essence.ChickenEssence, 1, 0);
        ResourceRecipes.cowEssence = new ItemStack(Essence.CowEssence, 1, 0);
        ResourceRecipes.pigEssence = new ItemStack(Essence.PigEssence, 1, 0);
        ResourceRecipes.sheepEssence = new ItemStack(Essence.SheepEssence, 1, 0);
    }
}
